/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_clulab_transformers_tokenizer_jni_JavaJniTokenizer */

#ifndef _Included_org_clulab_transformers_tokenizer_jni_JavaJniTokenizer
#define _Included_org_clulab_transformers_tokenizer_jni_JavaJniTokenizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_clulab_transformers_tokenizer_jni_JavaJniTokenizer
 * Method:    native_create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_clulab_transformers_tokenizer_jni_JavaJniTokenizer_native_1create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_clulab_transformers_tokenizer_jni_JavaJniTokenizer
 * Method:    native_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_clulab_transformers_tokenizer_jni_JavaJniTokenizer_native_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_clulab_transformers_tokenizer_jni_JavaJniTokenizer
 * Method:    native_tokenize
 * Signature: (J[Ljava/lang/String;)Lorg/clulab/transformers/tokenizer/jni/JavaJniTokenization;
 */
JNIEXPORT jobject JNICALL Java_org_clulab_transformers_tokenizer_jni_JavaJniTokenizer_native_1tokenize
  (JNIEnv *, jclass, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
